repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  
  - repo: local
    hooks:
      - id: docformatter
        name: docformatter
        entry: docformatter
        language: python
        additional_dependencies: [docformatter==1.7.5]
        args: [--wrap-summaries, "88", --wrap-descriptions, "88", --in-place]
        types: [python]